# Generated by Django 3.2.3 on 2021-07-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_authentication', '0004_remove_costumuser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_authentication.costumuser')),
                ('profile_bio', models.TextField(blank=True)),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
                ('profile_updated', models.DateTimeField(auto_now=True)),
                ('profile_block_list', models.ManyToManyField(related_name='_profiles_profile_profile_block_list_+', through='profiles.Profile', to='profiles.Profile')),
                ('profile_followers', models.ManyToManyField(related_name='_profiles_profile_profile_followers_+', through='profiles.Follower', to='profiles.Profile')),
                ('profile_friends', models.ManyToManyField(related_name='_profiles_profile_profile_friends_+', through='profiles.Friend', to='profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='profile_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_friends', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='profile_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_follower', to='profiles.profile'),
        ),
    ]
