# Generated by Django 3.2.2 on 2021-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField(blank=True, null=True)),
                ('tweet_image', models.ImageField(upload_to='')),
                ('tweet_created', models.DateField(auto_now_add=True)),
                ('tweet_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
