# Generated by Django 3.2.2 on 2021-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210510_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
