# Generated by Django 3.2.3 on 2021-06-11 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0005_auto_20210611_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_like_user', through='tweets.TweetLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
