# Generated by Django 3.2.3 on 2021-07-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('api_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='token',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
